apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  # If you don't want to specify a name for each TaskRun,you can use the `generateName` attribute to let Tekton pick a random
  # one from string you defined
  generateName: build-app-run-
  labels:
    app.kubernetes.io/managed-by: tekton-pipelines
    tekton.dev/task: build-app
  namespace: default
spec:
  debug:
    breakpoint: ["onFailure"]
  params:
  - name: contextDir
    value: quarkus
  - name: revision
    value: master
  - name: sslVerify
    value: "false"
  - name: subdirectory
    value: ""
  - name: tlsVerify
    value: "false"
  - name: url
    value: https://github.com/gitops-cookbook/tekton-tutorial-greete.git
  serviceAccountName: default
  # here you list the Task that the TaskRun is reffering to
  taskRef:
    kind: Task
    name: build-app
  timeout: 1h0m0s
  workspaces:
  - emptyDir: {}
    name: source
